### PR TITLE
Refactor improve code more readability and simplicity

### PR DESCRIPTION
**Pull request by yunusemrejs**

### CODE REVIEW

**Review by yatki — APPROVED** [review]
Great stuff :D

**Review by LordReydrX — APPROVED** [review]
thx

**Review by LordReydrX — APPROVED** [review]
thx

**Review by BankPansuwan — APPROVED** [review]

**Review by BankPansuwan — APPROVED** [review]

**Review by BankPansuwan — CHANGES_REQUESTED** [review]
7143cf67fcb140623102dcfb0432ea29012a01f9

**Pull request merged**
