### PR TITLE
add language field as a filter

### PR DESCRIPTION
**Pull request by woodgear**

### CODE REVIEW

**Comment by woodgear** [comment]
i glad to know what your idea about that.maybe some different implement method?

**Comment by martinandersen3d** [comment]
Please merge this feature :D Really need it :D

**Comment by yatki** [comment]
@woodgear So sorry for the late reply. Thank you very much for the PR. I actually have a different solution for this using vscode's native snippet support. I was writing a migration script when I was interrupted with other stuff.

I'll look into this get back to you in a few days.

**Comment by woodgear** [comment]
is there some news?

**Comment by yatki** [comment]
@woodgear yes. I was looking into a nice way to detect all snippets that vscode loads. However, seems like it's not a viable option at the moment because vscode API is not supporting that. 

The good news is I came up with a nice way to organize snippets. 

I'm going to close this PR for the moment. Because we need to allow users to define multiple languages for a snippet. Thank you very much for your efforts and interest. 

I'll publish the new version very soon. 🖖 👨‍🚀

**Pull request closed without merging**
